// This file was autogenerated by calcdeps.py
goog.addDependency("../../../mvc/mvc/controller.js", ['mvc.controller'], []);
goog.addDependency("../../../mvc/mvc/history.js", ['mvc.history'], []);
goog.addDependency("../../../mvc/mvc/view.js", ['mvc.View'], ['mvc.Model', 'goog.ui.Component']);
goog.addDependency("../../../mvc/mvc/model.js", ['mvc.Model', 'mvc.Model.EventType'], ['goog.events', 'goog.events.Event', 'goog.events.EventTarget', 'goog.net.XhrIo', 'goog.json']);
